apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
      env: dev
  template:
    metadata:
      name: nginx
      labels:
        app: web
        env: dev
    spec:
      containers:
        - name: nginx
          image: nginx:1.17.2-alpine
