apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-volume-1
  labels:
    app: web
    type: storage
spec:
  storageClassName: slow
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/pv0001"

apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-volume-2
  labels:
    app: web
    type: storage
spec:
  storageClassName: slow
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/pv0002"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-volume-3
  labels:
    app: web
    type: storage
spec:
  storageClassName: slow
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/pv0003"

---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: default
  labels:
    app: weblog
    env: dev
type: Opaque
data:
  root_username: YWRtaW4=
  root_password: UGFzc3cwcmQ=
  keyfile: dk5uMG9iOW5hM09oWGo0dTRhU0psdDRQM1k4L3pRTW1xV0VrYm5tQnRpRVBrbkd6Mzd4UWQ5MEE1Zmh5ZzBNUDFra1FuL1NmeU1jaE5xanNwZzI0RXdHVzBQQmdBRGNFcVVaaU5xK2FIVjdkdUVQZFNQOVZ3b1NPSEJRb0MrL085NG1VZU5QMExjeDViNEdTL2VKUTFWaEhQYlFHSlE2RTl5cVJIRFBZVk5NRFpHV215ZnFyNlZaV0hqamNGRUlWeHZVK0dJakhjTVVZbGRaN0RCVFVFZWhra1FydDJDbFRVSTZTeG1qd253RmhyMklheEdiUHVsNmRJSmMyL2JFb1A2MGFvSDBlbDdhOWlUejN3R3JvZ3VmWE9uVUs1d3l6VXp5YUx3bC9adldPMkttaUFWTnhTb2FIOXVwY3hYZTF5cXhZZUk5VE9iSHZWakxRY3lzTUFvb2t2Nm1vbHZTN0pFbU1qdWdsdVBHczQzWDI3aVdtMXY1N0ZXUGV0R08xUFlMdXF0YWQ4aDdJZDNBVldXVUthYlJoNjByVUdWTFcrZlJ3RUlIN2hMdGQ5L3RPdE5JMkJSNk40WDNYNnB1K0d1ZVRnaUtSZ0F1emhid2FkY1lnN21oei9GRzkxaGdHTnp1SzlpZWZlWG0zK2hPTHJIMTVjOFlrRHNXVTBmOUt2TVV5andiaDNKNFZKU3JYbXpra0VLbUFPOVVFUUYwMm10MXVEc2ZlSDRGRUdnaDBEempKY3RZclVHVFZKZzF5SXB4dTJMTVV5T2RBUGNla1hITTREdVZHTW5Gek9qVC9saVRPUFkvOTRoMWVlVzk3cWd1TUJBR2plKzdaZjZxbHhOcHZMbFpYM1pwSUtGSE9mVVJVMWZwQWVVc29DOHA3QkN1ZS93M3ZQNWRzTldNT3hyQjhKYk05aEtIWTdsVWU5UGZkL05qT1hLNy9Sa3lsaFhkTzFDU014Z2dVSXY0ZmdvU0RSNDhVbGZuVzRaUzBISHVtWG8wODE2aFZNRFVydjM3OUtkNEdRdGJHWjRPaktGK3o5WEl5aHZmeThXSzJieUNhRExtWXEybUZFS1VVNEI1TnhMbVhJbFZ3UlpreTg5OHpGaTdXdmIwcWh0TUhCd3FLcHBDVkJ0ZWM0V3h0TzQ3Z29wMDFMem1VUS9hQ2c4SThKR293TzFubWZMMkFIVFBlNmRYbzY0NFJCMkE3MmNYMXdHQ3NjSGY2ak9LV0w2bjVpcDhZMTNKVEo2WERwa0RxZitLU05XTDJ3NWFZWUR4MnJFM00wcnZkTmVXVmdzcXcyN2h5aFZ6ZlVOUWFDSG9lU3dsa3pKbTlNTEJ2Z2NlOENNbjJvaWZpZ0N0VAo=

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: web
    type: database
spec:
  selector:
    matchLabels:
      app: web
      type: database
  serviceName: db-svc
  replicas: 3
  template:
    metadata:
      name: mongodb
      labels:
        app: web
        type: database
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
        - name: secret
          secret:
            secretName: mongo-secret
            items:
              - key: keyfile
                path: keyfile
                mode: 0700
      containers:
        - name: mongodb
          image: weblog-db:v1.0.0
          imagePullPolicy: Never
          env:
            - name: "MONGO_INITDB_ROOT_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: root_username
            - name: "MONGO_INITDB_ROOT_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: root_password
            - name: "MONGO_INITDB_DATABASE"
              value: "admin"
          volumeMounts:
            - mountPath: "/data/db"
              name: storage
            - mountPath: /home/mongodb
              name: secret
          args:
            - "mongod"
            - "--auth"
            - "clusterAuthMode=keyFile"
            - "--keyFile=/home/mongodb/keyfile"
            - "--replSet=rs0"
            - "--bind_ip_all"
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        storageClassName: slow
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 1Gi
