apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-volume
  labels:
    app: web
    type: storage
spec:
  storageClassName: slow
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/storage"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-claim
  labels:
    app: web
    type: storage
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: web
    type: database
spec:
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: storage-claim
  containers:
    - name: mongodb
      image: weblog-db:v1.0.0
      imagePullPolicy: Never
      volumeMounts:
        - mountPath: "/data/db"
          name: storage
      command:
        - "mongod"
        - "--binnd_ip_all"
