apiVersion: v1
kind: Secret
metadata:
  name: secret-sample-secret
data:
  secret-key1: c2VjcmV0LXZhbHVlMQ==
  secret-key2: c2VjcmV0LXZhbHVlMgo=

---
apiVersion: v1
kind: Pod
metadata:
  name: secret-sample-pod
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx:1.17.2-alpine
    env:
    - name: SECRET_KEY1
      valueFrom:
        secretKeyRef:
          name: secret-sample-secret
          key: secret-key1
    volumeMounts:
    - name: secret-storage1
      mountPath: /home/nginx
  volumes:
  - name: secret-storage1
    secret:
      secretName: secret-sample-secret
      items:
        - key: secret-key2
          path: secret-key2
