apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: web
    env: dev
spec:
  containers:
    - name: nginx
      image: nginx:1.17.3-alpine

---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  type: NodePort
  selector:
    app: web
    env: dev
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
