apiVersion: v1
kind: PersistentVolume
metadata:
  name: statefulset-sample-volume
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/storage

---
apiVersion: v1
kind: Service
metadata:
  name: statefulset-sample-service
spec:
  clusterIP: None
  selector:
    app: web
    env: study
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-sample-statefulset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      env: dev
  revisionHistoryLimit: 14
  serviceName: statefulset-sample-service
  template:
    metadata:
      name: statefulset-sample-pod
      labels:
        app: web
        env: dev
    spec:
      containers:
        - name: nginx
          image: nginx:1.17.3-alpine
          volumeMounts:
            - name: storage
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        storageClassName: slow
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 1Gi
