apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-sample-volume
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/storage"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-sample-volume-claim
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: persistent-sample-pod
  labels:
    app: web
    env: dev
spec:
  volumes:
    - name: persistent-sample-pod-volume
      persistentVolumeClaim:
        claimName: persistent-sample-volume-claim
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: persistent-sample-pod-volume

---
apiVersion: v1
kind: Service
metadata:
  name: kind-port-mappings-service
spec:
  type: NodePort
  selector:
    app: web
    env: dev
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
