apiVersion: v1
kind: Pod
metadata:
  name: nginx
  # namespaceを指定しない場合はdefaultが指定されたとみなされる
  # namespace: default
  labels:
    app: nginx
    env: study
spec:
  containers:
    - name: nginx
      image: nginx:1.17.2-alpine
